#ifndef POKEPLATINUM_CONSTANTS_BALL_CAPSULES_H
#define POKEPLATINUM_CONSTANTS_BALL_CAPSULES_H

#include "generated/seals.h"

#define TOTAL_CAPSULES     12
#define SEALS_PER_CAPSULE  8
#define MAX_SEALS_PER_TYPE 99

#define BALL_CAPSULE_EDITOR_BALL_CENTER_X 190
#define BALL_CAPSULE_EDITOR_BALL_CENTER_Y 70
#define BALL_CAPSULE_EDITOR_BALL_RADIUS   60

#endif // POKEPLATINUM_CONSTANTS_BALL_CAPSULES_H
